### ISSUE TITLE
IPO Package

### ISSUE THREAD

**Issue by cuevasj14** [F18MIS4173Team1/Team1#13]
a.List of programs planned with a description of what each program will do
b.Pseudocode, Flowchart or IPO chart which outlines the processes and logic of each program
c. Inputs and outputs for each program. (may be included in IPO chart if you chose IPO to outline your processes)

**Comment by pricej15** [comment]
[IPO charts.docx](https://github.com/F18MIS4173Team1/Team1/files/2498442/IPO.charts.docx)
